[package]
name = "xairo"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "xairo"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
png = "0.11.0"
cairo-rs = { version = "0.14.0", features = ["png"] }
